import { eq, desc, inArray } from "drizzle-orm";
import { db } from "../../db";
import {
  pullRequests,
  prReviews,
  prIssues,
  connectedRepositories,
  githubInstallations,
  type PullRequest,
  type PRReview,
  type PRIssue,
} from "../../db/schema";
import { env } from "../../configs/env";
import { getInstallationOctokitForRepo } from "../github/github-app.service";

const AI_SERVICE_URL = process.env.AI_SERVICE_URL || "http://127.0.0.1:8000";

export async function listPullRequests(repoFullName?: string) {
  if (repoFullName) {
    const prs = await db
      .select()
      .from(pullRequests)
      .where(eq(pullRequests.repoFullName, repoFullName))
      .orderBy(desc(pullRequests.createdAt));
    return enrichPRsWithReviewData(prs);
  }

  const prs = await db
    .select()
    .from(pullRequests)
    .orderBy(desc(pullRequests.createdAt));
  return enrichPRsWithReviewData(prs);
}

async function enrichPRsWithReviewData(prs: PullRequest[]) {
  const result = [];
  for (const pr of prs) {
    const [review] = await db
      .select()
      .from(prReviews)
      .where(eq(prReviews.pullRequestId, pr.id))
      .limit(1);

    let issues: PRIssue[] = [];
    if (review) {
      issues = await db
        .select()
        .from(prIssues)
        .where(eq(prIssues.reviewId, review.id));
    }

    result.push({
      ...pr,
      review: review || null,
      issues,
    });
  }
  return result;
}

export async function getPullRequestDetails(prId: string) {
  const [pr] = await db
    .select()
    .from(pullRequests)
    .where(eq(pullRequests.id, prId))
    .limit(1);

  if (!pr) return null;

  const [review] = await db
    .select()
    .from(prReviews)
    .where(eq(prReviews.pullRequestId, pr.id))
    .limit(1);

  let issues: PRIssue[] = [];
  if (review) {
    issues = await db
      .select()
      .from(prIssues)
      .where(eq(prIssues.reviewId, review.id));
  }

  return {
    ...pr,
    review: review || null,
    issues,
  };
}

export async function evaluatePRWithAIService(prId: string) {
  const pr = await getPullRequestDetails(prId);
  if (!pr) throw new Error("PR not found");

  // AI Fix PR Guardrail: Check if PR is generated by AI agent
  if (pr.headBranch.startsWith("ai-fix/") || pr.title.toLowerCase().startsWith("[ai fix]")) {
    await db
      .update(pullRequests)
      .set({ status: "skipped_ai_fix" })
      .where(eq(pullRequests.id, prId));

    return {
      status: "skipped_ai_fix",
      reason: "PR was generated by AI Agent fix workflow (ai-fix/* branch). Review skipped to prevent feedback loops.",
    };
  }

  // Fetch raw GitHub patch diff for line-level code inspection
  let diffText = "";
  try {
    const diffRes = await fetch(`https://github.com/${pr.repoFullName}/pull/${pr.prNumber}.diff`, {
      headers: { "User-Agent": "Sentinel-AI-PR-Reviewer" },
    });
    if (diffRes.ok) {
      diffText = await diffRes.text();
    }
  } catch (e) {
    console.warn("Could not fetch raw GitHub PR diff:", e);
  }

  // Call AI Service PR review endpoint
  const response = await fetch(`${AI_SERVICE_URL}/api/pr/review`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      repo_id: pr.repoFullName,
      pr_number: pr.prNumber,
      base_branch: pr.baseBranch,
      head_branch: pr.headBranch,
      title: pr.title,
      body: pr.body || "",
      diff_text: diffText,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`AI Service review failed: ${errText}`);
  }

  const data = await response.json();

  // Save/update review
  const existingReview = pr.review;
  let reviewId: string;

  if (existingReview) {
    reviewId = existingReview.id;
    await db
      .update(prReviews)
      .set({
        verdict: data.verdict || "SUGGEST",
        riskScore: data.risk_score || 0.0,
        summary: data.summary || "Agentic PR review completed.",
        agentRationale: data.agent_rationale || "",
        rawReviewJson: data,
      })
      .where(eq(prReviews.id, reviewId));

    // Delete previous issues for this review before inserting fresh ones
    await db.delete(prIssues).where(eq(prIssues.reviewId, reviewId));
  } else {
    const [newReview] = await db
      .insert(prReviews)
      .values({
        pullRequestId: pr.id,
        verdict: data.verdict || "SUGGEST",
        riskScore: data.risk_score || 0.0,
        summary: data.summary || "Agentic PR review completed.",
        agentRationale: data.agent_rationale || "",
        rawReviewJson: data,
      })
      .returning();
    reviewId = newReview!.id;
  }

  // Insert structured checklist issues
  const issuesList = data.issues || [];
  for (const item of issuesList) {
    await db.insert(prIssues).values({
      reviewId,
      title: item.title || item.description || "PR Code Improvement",
      description: item.description || item.title || "",
      category: item.category || "bug",
      severity: item.severity || "warning",
      filePath: item.file_path || "codebase",
      line: item.line || 1,
      suggestedFix: item.suggested_fix || item.fix_patch || "",
      isFixed: false,
    });
  }

  // Update PR status
  await db
    .update(pullRequests)
    .set({ status: "reviewed" })
    .where(eq(pullRequests.id, pr.id));

  return getPullRequestDetails(pr.id);
}

export async function fixSelectedPRIssues(prId: string, issueIds: string[]) {
  const pr = await getPullRequestDetails(prId);
  if (!pr) throw new Error("PR not found");

  if (!issueIds || issueIds.length === 0) {
    throw new Error("No issues selected for AI fixing");
  }

  // Fetch selected issues
  const selectedIssues = await db
    .select()
    .from(prIssues)
    .where(inArray(prIssues.id, issueIds));

  if (selectedIssues.length === 0) {
    throw new Error("Selected issues not found");
  }

  // Fetch GitHub file contents for each affected file so the AI fixer has the real source
  const githubToken = (process.env.GITHUB_TOKEN || process.env.GITHUB_PAT || env.GITHUB_TOKEN || "").trim();
  const uniqueFilePaths = [...new Set(selectedIssues.map((i) => i.filePath))];
  const existingFileContents: Record<string, string> = {};

  for (const filePath of uniqueFilePaths) {
    try {
      const headers: Record<string, string> = {
        Accept: "application/vnd.github.v3.raw",
        "User-Agent": "Sentinel-AI-Agent",
      };
      if (githubToken) {
        headers.Authorization = `Bearer ${githubToken}`;
      }
      const fileUrl = `https://api.github.com/repos/${pr.repoFullName}/contents/${filePath}?ref=${pr.headBranch}`;
      const fileResp = await fetch(fileUrl, { headers });
      if (fileResp.ok) {
        existingFileContents[filePath] = await fileResp.text();
      }
    } catch (e) {
      console.warn(`⚠️ Could not fetch ${filePath} from GitHub:`, e);
    }
  }

  // Fetch PR diff for context
  let diffText = "";
  try {
    const diffUrl = `https://github.com/${pr.repoFullName}/pull/${pr.prNumber}.diff`;
    const diffResp = await fetch(diffUrl);
    if (diffResp.ok) {
      diffText = await diffResp.text();
    }
  } catch {
    // diff is optional context
  }

  // Request AI Service to generate SURGICAL patch fixes for selected issues
  const aiResponse = await fetch(`${AI_SERVICE_URL}/api/pr/fix`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      repo_id: pr.repoFullName,
      pr_number: pr.prNumber,
      base_branch: pr.headBranch,
      diff_text: diffText.slice(0, 5000),
      existing_file_contents: existingFileContents,
      issues: selectedIssues.map((i) => ({
        id: i.id,
        title: i.title,
        description: i.description,
        file_path: i.filePath,
        line: i.line,
        category: i.category,
        suggested_fix: i.suggestedFix,
      })),
    }),
  });

  if (!aiResponse.ok) {
    const errText = await aiResponse.text();
    throw new Error(`AI Service fix patch generation failed: ${errText}`);
  }

  const fixResult = await aiResponse.json();
  const fileFixes: Array<{ file_path: string; content: string }> = fixResult.file_fixes || [];

  if (fileFixes.length === 0) {
    throw new Error("AI Agent did not return any modified file contents");
  }

  const [owner, repoName] = pr.repoFullName.split("/");
  const newBranchName = `ai-fix/pr-${pr.prNumber}-${Date.now()}`;
  let fixPrUrl = "";

  if (githubToken) {
    // -----------------------------------------------------------------------
    // Standard GitHub REST API execution via fetch (Deployment Friendly)
    // -----------------------------------------------------------------------
    const headers = {
      Authorization: `Bearer ${githubToken}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "Sentinel-AI-Fix-Agent",
      "Content-Type": "application/json",
    };

    try {
      // 1. Get base branch SHA
      const refRes = await fetch(`https://api.github.com/repos/${pr.repoFullName}/git/ref/heads/${pr.headBranch}`, { headers });
      if (!refRes.ok) {
        const refErr = await refRes.text();
        if (refRes.status === 403 || refRes.status === 404) {
          throw new Error(
            `GitHub Permission Denied: GITHUB_TOKEN lacks read/write permissions for '${pr.repoFullName}'.`
          );
        }
        throw new Error(`Failed to fetch ref for branch '${pr.headBranch}': ${refErr}`);
      }
      const refData = await refRes.json();
      const baseSha = refData.object.sha;

      // 2. Create new branch
      const createBranchRes = await fetch(`https://api.github.com/repos/${pr.repoFullName}/git/refs`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          ref: `refs/heads/${newBranchName}`,
          sha: baseSha,
        }),
      });
      if (!createBranchRes.ok) {
        const branchErr = await createBranchRes.text();
        if (createBranchRes.status === 403 || createBranchRes.status === 404) {
          throw new Error(
            `GitHub Write Permission Denied: Your GITHUB_TOKEN does not have permission to push branches to '${pr.repoFullName}'. You can only push AI fix branches to repositories you own or have write access to.`
          );
        }
        throw new Error(`Failed to create branch '${newBranchName}': ${branchErr}`);
      }

      // 3. Commit modified files to new branch
      for (const fileFix of fileFixes) {
        let currentSha: string | undefined = undefined;
        try {
          const fileRes = await fetch(`https://api.github.com/repos/${pr.repoFullName}/contents/${fileFix.file_path}?ref=${newBranchName}`, { headers });
          if (fileRes.ok) {
            const fileData = await fileRes.json();
            currentSha = fileData.sha;
          }
        } catch {
          // File might be new
        }

        const putRes = await fetch(`https://api.github.com/repos/${pr.repoFullName}/contents/${fileFix.file_path}`, {
          method: "PUT",
          headers,
          body: JSON.stringify({
            message: `fix(ai): resolve automated PR issue in ${fileFix.file_path}`,
            content: Buffer.from(fileFix.content).toString("base64"),
            branch: newBranchName,
            sha: currentSha,
          }),
        });

        if (!putRes.ok) {
          throw new Error(`Failed to commit file '${fileFix.file_path}': ${await putRes.text()}`);
        }
      }

      // 4. Create Pull Request
      const prRes = await fetch(`https://api.github.com/repos/${pr.repoFullName}/pulls`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          title: `[AI Fix] Resolve ${selectedIssues.length} issue(s) for PR #${pr.prNumber}`,
          head: newBranchName,
          base: pr.headBranch,
          body:
            `🤖 **AI Automated PR Fix**\n\nThis PR was automatically raised by the Sentinel AI Agent to resolve the following selected issues from PR #${pr.prNumber}:\n\n` +
            selectedIssues.map((i) => `- **${i.title}** (\`${i.filePath}:${i.line}\`)`).join("\n"),
        }),
      });

      if (!prRes.ok) {
        throw new Error(`Failed to create GitHub Pull Request: ${await prRes.text()}`);
      }

      const prData = await prRes.json();
      fixPrUrl = prData.html_url;
    } catch (err: any) {
      console.error("❌ GitHub Token REST API Error:", err);
      throw new Error(`GitHub PR Creation failed: ${err.message || err}`);
    }
  } else {
    // Fallback: GitHub App Octokit
    let octokit;
    try {
      octokit = await getInstallationOctokitForRepo(owner, repoName);
    } catch (e: any) {
      throw new Error(`GitHub Authentication Notice: Please set GITHUB_TOKEN=ghp_... in backend/api-service/.env to enable automated PR creation.`);
    }

    if (!octokit) {
      throw new Error(
        `GitHub Authentication Notice: Please set GITHUB_TOKEN=ghp_... in backend/api-service/.env to enable automated PR creation.`
      );
    }

    try {
      const { data: refData } = await octokit.request("GET /repos/{owner}/{repo}/git/ref/{ref}", {
        owner,
        repo: repoName,
        ref: `heads/${pr.headBranch}`,
      });
      const baseSha = refData.object.sha;

      await octokit.request("POST /repos/{owner}/{repo}/git/refs", {
        owner,
        repo: repoName,
        ref: `refs/heads/${newBranchName}`,
        sha: baseSha,
      });

      for (const fileFix of fileFixes) {
        let currentSha: string | undefined = undefined;
        try {
          const { data: fileData } = await octokit.request("GET /repos/{owner}/{repo}/contents/{path}", {
            owner,
            repo: repoName,
            path: fileFix.file_path,
            ref: newBranchName,
          });
          if (!Array.isArray(fileData)) {
            currentSha = fileData.sha;
          }
        } catch {
          // File might be new
        }

        await octokit.request("PUT /repos/{owner}/{repo}/contents/{path}", {
          owner,
          repo: repoName,
          path: fileFix.file_path,
          message: `fix(ai): resolve automated PR issue in ${fileFix.file_path}`,
          content: Buffer.from(fileFix.content).toString("base64"),
          branch: newBranchName,
          sha: currentSha,
        });
      }

      const { data: newPrData } = await octokit.request("POST /repos/{owner}/{repo}/pulls", {
        owner,
        repo: repoName,
        title: `[AI Fix] Resolve ${selectedIssues.length} issue(s) for PR #${pr.prNumber}`,
        head: newBranchName,
        base: pr.headBranch,
        body:
          `🤖 **AI Automated PR Fix**\n\nThis PR was automatically raised by the Sentinel AI Agent to resolve the following selected issues from PR #${pr.prNumber}:\n\n` +
          selectedIssues.map((i) => `- **${i.title}** (\`${i.filePath}:${i.line}\`)`).join("\n"),
      });

      fixPrUrl = newPrData.html_url;
    } catch (err: any) {
      console.error("❌ GitHub Octokit error while pushing fix branch:", err);
      throw new Error(`GitHub PR Creation failed: ${err.message || err}`);
    }
  }

  // Mark selected issues as fixed
  for (const issueId of issueIds) {
    await db
      .update(prIssues)
      .set({
        isFixed: true,
        fixPrUrl,
      })
      .where(eq(prIssues.id, issueId));
  }

  return {
    success: true,
    branch: newBranchName,
    fixPrUrl,
    fixedIssuesCount: selectedIssues.length,
  };
}
