"""BaseVectorStore protocol shared by all concrete vector store implementations."""
from typing import Protocol, List, Optional, Dict, Any, runtime_checkable


@runtime_checkable
class BaseVectorStore(Protocol):
    """
    Protocol that every vector store backend must satisfy.
    The interface mirrors the ChromaDB collection API so VectorKBClient
    can delegate to any backend without changing callers.
    """

    batch_size: int
    """Maximum number of documents to upsert in a single API call."""

    def upsert(
        self,
        ids: List[str],
        documents: List[str],
        metadatas: List[Dict[str, Any]],
        embeddings: Optional[List[List[float]]] = None,
    ) -> None:
        """Insert or update documents. Embeddings are generated by the store if not supplied."""
        ...

    def query(
        self,
        query_texts: List[str],
        n_results: int = 5,
        where: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Semantic similarity search.
        Returns a dict with keys: ids, documents, metadatas, distances.
        Each value is a list-of-lists (one inner list per query).
        """
        ...

    def delete(self, where: Dict[str, Any]) -> None:
        """Delete all documents matching the metadata filter."""
        ...

    def get(
        self,
        where: Dict[str, Any],
        include: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Retrieve documents and/or metadata matching the filter."""
        ...

    def update(self, ids: List[str], metadatas: List[Dict[str, Any]]) -> None:
        """Update metadata for existing document IDs."""
        ...

    def count(self) -> int:
        """Return total document count in the vector store."""
        ...

    def get_distinct_repos(self) -> List[str]:
        """Return list of unique repository identifiers stored in metadata."""
        ...

